import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Phone, MapPin, Plus, ChevronLeft, ChevronRight } from 'lucide-react';
import { RESTAURANT_INFO as info } from './data/restaurantData';

const menuUrl = 'https://linktr.ee/Elasadormargaritaranch/';
const highlights = [
  { name: 'Ribeye from the grill', description: 'A centerpiece for guests who come hungry.', image: '/images/grill.webp' },
  { name: 'Homemade tortillas', description: 'Warm tortillas made for sharing around the table.', image: '/images/tacos.webp' },
  { name: 'Carne asada', description: 'Grilled beef served with the flavors of northern Mexico.', image: '/images/platter.webp' },
];
const menuGroups = [
  { title: 'Appetizers', items: [
    ['Guacamole & Chips', '$7'], ['French Fries', '$7'], ['Charro Beans', '$4'],
    ['Grilled Potatoes with Meat', '$12'], ['Carne Asada Quesadilla', '$12'],
  ]},
  { title: 'Entrées', note: 'Served with charro beans, rice, grilled onions and jalapeño.', items: [
    ['Ribeye Steak — Regular', '$22'], ['Ribeye Steak — Premium', '$25'], ['T-Bone Steak', '$20'],
    ['Skirt Steak', '$22'], ['Sausage', '$15'], ['Grilled Chicken Wings & Thighs', '$15'],
    ['Northern-Style Beef Ribs', '$18'], ['Pork Ribs', '$18'], ['Grilled Chicken with Fries', '$18'],
    ['Burrito with Your Choice of Meat', '$15'], ['Flautas', '$12'], ['Torta', '$18'],
    ['Chilaquiles', '$15'], ['Nachos Supreme', '$18'], ['Hamburger with Fries', '$12'],
    ['Cheeseburger with Fries', '$12'], ['Bacon Cheeseburger with Fries', '$15'],
    ['Tostada with Cheese & Side Salad', '$3 each'], ['Tostada with Cheese, Meat & Side Salad', '$7 each'],
  ]},
  { title: 'Tacos', note: '$5 each · Served with beans, grilled onions and jalapeño.', items: [
    ['Tripas', '$5'], ['Chicken', '$5'], ['Steak', '$5'], ['Ribeye', '$5'], ['Carnitas', '$5'], ['Barbacoa', '$5'], ['Skirt Steak', '$5'],
  ]},
  { title: 'Drinks', items: [
    ['Bottled Water', '$2'], ['Mexican Coke', '$5'], ['Jarritos Orange', '$4'], ['Powerade', '$3'], ['Coca-Cola', '$3'], ['Sprite', '$3'], ['Lemonade · 2 refills', '$5'],
  ]},
];
const hours = [
  ['Monday', 'Closed'], ['Tuesday', '12:00 PM – 8:00 PM'], ['Wednesday – Thursday', '10:30 AM – 8:00 PM'],
  ['Friday – Saturday', '10:30 AM – 10:00 PM'], ['Sunday', '10:30 AM – 7:00 PM'],
];
const photos = [{ src: '/images/el-asador-patio.jpg', title: 'Welcome to El Asador', alt: 'The covered patio entrance at El Asador Margarita Ranch Grill' }, ...highlights.map(x => ({ src: x.image, title: x.name, alt: x.name }))];
type Panel = 'contact' | 'gallery' | null;
function Brand() { return <span className="brand-name">EL ASADOR<small>MARGARITA RANCH GRILL</small></span>; }

export default function App() {
  const [navOpen, setNavOpen] = useState(false);
  const [panel, setPanel] = useState<Panel>(null);
  const [photo, setPhoto] = useState(0);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const el = dialog.current; if (!el || !panel) return; const previous = document.activeElement as HTMLElement; el.showModal(); document.body.style.overflow = 'hidden'; return () => { el.close(); document.body.style.overflow = ''; previous?.focus(); }; }, [panel]);
  useEffect(() => { if (!navOpen) return; const close = (e: KeyboardEvent) => { if (e.key === 'Escape') { setNavOpen(false); document.getElementById('nav-toggle')?.focus(); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [navOpen]);
  const closeNav = () => setNavOpen(false);
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a href="#home" className="brand" aria-label="El Asador home" onClick={closeNav}><Brand /></a><nav aria-label="Main navigation" className={navOpen ? 'main-nav expanded' : 'main-nav'} id="main-nav"><a href="#menu" onClick={closeNav}>The menu</a><a href="#story" onClick={closeNav}>Our story</a><a href="#experience" onClick={closeNav}>The patio</a><a href="#visit" onClick={closeNav}>Find us</a></nav><div className="header-actions"><a className="button small header-book" href={menuUrl} target="_blank" rel="noreferrer">Menu & prices <ArrowUpRight size={16} /></a><button className="nav-toggle" id="nav-toggle" aria-label={navOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={navOpen} aria-controls="main-nav" onClick={() => setNavOpen(!navOpen)}>{navOpen ? <X /> : <Menu />}</button></div></header>
    <main id="main">
      <section className="hero" id="home" aria-labelledby="hero-title"><img className="hero-image" srcSet="/images/grill-mobile.webp 800w, /images/grill.webp 1800w" sizes="100vw" src="/images/grill.webp" alt="A generous platter of grilled meat and vegetables" fetchPriority="high" width="1800" height="1200" /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow light"><span /> EAST AUSTIN, TEXAS <span /></p><h1 id="hero-title">Good food.<br /><em>Great company.</em><br />A little fire.</h1><p className="hero-description">Mexican grill favorites.<br />A welcoming spot on East 7th Street.</p><div className="hero-buttons"><a className="button" href={menuUrl} target="_blank" rel="noreferrer">View menu & prices <ArrowUpRight size={18} /></a><button className="button outline-button" onClick={() => setPanel('contact')}>Call & visit</button></div></div><div className="hero-bottom"><span>EL ASADOR · MARGARITA RANCH GRILL</span><a href="#signatures">PULL UP A CHAIR <ArrowDown size={17} /></a><span>2617 E 7TH ST, AUSTIN</span></div></section>
      <div className="ribbon"><span>DEL ASADOR A TU MESA</span><span aria-hidden="true">✳</span><span>FROM THE GRILL TO YOUR TABLE</span><span aria-hidden="true">✳</span><span>EAST AUSTIN, TEXAS</span></div>
      <section className="section signatures" id="signatures"><div className="section-heading"><div><p className="eyebrow">01 / A TASTE OF EL ASADOR</p><h2>Start with<br /><em>something from the grill.</em></h2></div><div className="heading-aside"><p>Ribeye, carne asada and homemade tortillas<br />bring the table together.</p><a className="text-link" href={menuUrl} target="_blank" rel="noreferrer">Current menu & prices <ArrowUpRight size={18} /></a></div></div><div className="signature-grid">{highlights.map((item, i) => <article className="signature-card" key={item.name}><button className="dish-photo" aria-label={'Open photo: ' + item.name} onClick={() => { setPhoto(i + 1); setPanel('gallery'); }}><img src={item.image} alt={item.name} width="900" height="700" loading="lazy" /><span className="photo-number">0{i + 1}</span><span className="photo-action"><ArrowUpRight /></span></button><div className="dish-title"><h3>{item.name}</h3></div><p>{item.description}</p></article>)}</div></section>
      <section className="story section" id="story"><div className="story-title"><p className="eyebrow">02 / ROOTED IN THE ASADOR</p><h2>Mexican soul.<br /><em>Austin spirit.</em></h2></div><div className="story-copy"><p className="large-copy">There’s something special about a meal gathered around the grill.</p><p>El Asador Margarita Ranch Grill serves Mexican food in East Austin, with grilled meats and homemade tortillas at the heart of the experience.</p><p>Find the restaurant on East 7th Street, settle into the patio, and make time for good company.</p><a className="text-link" href="#visit">Come find us <ArrowUpRight size={18} /></a></div></section>
      <section className="menu-section section" id="menu"><div className="section-heading"><div><p className="eyebrow">03 / BUEN PROVECHO</p><h2>The full<br /><em>ranch grill menu.</em></h2></div><p className="menu-intro">Grilled over high heat, served without fuss,<br />and made for a hungry table.</p></div>{menuGroups.map(group => <section key={group.title} aria-labelledby={'menu-' + group.title.toLowerCase().replaceAll(' ', '-')}><div className="menu-controls"><div><p className="eyebrow">{group.title}</p>{group.note && <p>{group.note}</p>}</div></div><div className="menu-list">{group.items.map(([name, price]) => <article className="menu-item" key={name}><div><h3>{name}</h3></div><div className="menu-price"><span>{price}</span></div></article>)}</div></section>)}<div className="menu-foot"><p>Call or message the restaurant to order.</p><div className="dialog-actions"><a className="button" href={'tel:' + info.rawPhone}>Call now <Phone size={18} /></a><a className="button secondary" href="https://wa.me/15127703222" target="_blank" rel="noreferrer">Order on WhatsApp <ArrowUpRight size={18} /></a></div></div></section>
      <section className="experience" id="experience"><div className="experience-photo"><img src="/images/el-asador-patio.jpg" alt="Covered patio entrance at El Asador Margarita Ranch Grill with a colorful welcome sign" loading="lazy" width="1080" height="1920" /><span>THE PATIO · EL ASADOR, EAST 7TH STREET</span></div><div className="experience-copy"><p className="eyebrow light">04 / PULL UP A CHAIR</p><h2>Casual food.<br /><em>Colorful company.</em></h2><p>A covered, laid-back patio makes room for lunch, dinner and an easy meal with friends.</p><p>Come as you are, bring your appetite, and let the grill do the talking.</p><a className="button cream" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18} /></a><a className="text-link light-link" href={'tel:' + info.rawPhone}>Call the restaurant <Phone size={18} /></a></div></section>
      <section className="section gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">05 / THE EL ASADOR MOOD</p><h2>Fire. Flavor. <em>Feeling.</em></h2></div><p className="heading-aside">A colorful patio,<br />a hot grill and a shared table.</p></div><div className="gallery-grid">{photos.map((item, i) => <button key={item.src} onClick={() => { setPhoto(i); setPanel('gallery'); }} aria-label={'Open photo: ' + item.title}><img src={item.src} alt={item.alt} loading="lazy" width="800" height="700" /><span>{item.title}<Plus size={18} /></span></button>)}</div></section>
      <section className="visit section" id="visit"><div className="visit-intro"><p className="eyebrow">06 / COME SEE US</p><h2>Come hungry.<br /><em>Find us on 7th.</em></h2><address>{info.address}<br />{info.city}, {info.state} {info.zip}</address><a className="button" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18} /></a><a className="phone-link" href={'tel:' + info.rawPhone}><Phone size={17} />{info.phone}</a><a className="text-link" href="https://www.instagram.com/elasadormargaritaranch" target="_blank" rel="noreferrer">@elasadormargaritaranch <ArrowUpRight size={16} /></a></div><div className="hours"><h3>Opening hours</h3><dl>{hours.map(([day, time]) => <div key={day}><dt>{day}</dt><dd>{time}</dd></div>)}</dl><a className="text-link" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Google Maps updates <ArrowUpRight size={16} /></a></div><div className="visit-note"><MapPin size={26} /><h3>East Austin,<br />right on 7th.</h3><p>2617 East 7th Street.<br />Austin, Texas 78702.</p><a className="text-link" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Open Google Maps <ArrowUpRight size={18} /></a><hr /><p>Questions about the menu, pickup or seating?</p><a className="text-link" href="https://wa.me/15127703222" target="_blank" rel="noreferrer">Message on WhatsApp <ArrowUpRight size={17} /></a></div></section>
    </main>
    <footer><div className="footer-top"><a href="#home" className="brand"><Brand /></a><p>Good food brings us together.</p><a href="#home" className="text-link">Back to top <ArrowUpRight size={18} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} El Asador Margarita Ranch Grill</span><nav aria-label="Footer navigation"><a href={menuUrl} target="_blank" rel="noreferrer">Menu</a><a href="#visit">Hours & contact</a><a href="#gallery">Gallery</a></nav><span>AUSTIN, TEXAS</span></div></footer>
    <div className="mobile-actions"><a href={menuUrl} target="_blank" rel="noreferrer">Menu & prices</a><a href={'tel:' + info.rawPhone}>Call now <Phone size={17} /></a></div>
    <dialog ref={dialog} className={panel === 'gallery' ? 'modal photo-modal' : 'modal'} aria-labelledby="dialog-title" onCancel={() => setPanel(null)} onKeyDown={e => { if (panel === 'gallery' && (e.key === 'ArrowRight' || e.key === 'ArrowLeft')) { e.preventDefault(); setPhoto(i => (i + (e.key === 'ArrowRight' ? 1 : photos.length - 1)) % photos.length); } }}><button className="close-modal" aria-label="Close dialog" onClick={() => setPanel(null)}><X /></button>{panel === 'contact' && <><p className="eyebrow">LET’S GET TOGETHER</p><h2 id="dialog-title">Call or come by.</h2><p>Contact the restaurant about today’s menu, pickup, seating or group visits.</p><div className="call-card"><Phone /><a href={'tel:' + info.rawPhone}>{info.phone}</a><span>{info.fullAddress}</span></div><a className="button" href={'tel:' + info.rawPhone}>Call the restaurant <ArrowUpRight size={18} /></a><a className="text-link" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Directions & current hours <ArrowUpRight size={16} /></a></>}{panel === 'gallery' && <><h2 id="dialog-title" className="sr-only">{photos[photo].title}</h2><img className="lightbox-image" src={photos[photo].src} alt={photos[photo].alt} /><div className="gallery-caption"><button aria-label="Previous photo" onClick={() => setPhoto((photo + photos.length - 1) % photos.length)}><ChevronLeft /></button><div><strong>{photos[photo].title}</strong><p>{photo + 1} / {photos.length}</p></div><button aria-label="Next photo" onClick={() => setPhoto((photo + 1) % photos.length)}><ChevronRight /></button></div></>}</dialog>
  </>;
}
